### PR TITLE
[G2M] fix overlapped table borders

### LINKED ISSUE #16: Table borderline style overlapped
The issue is originated from `snoke-dashboard` branch

Screen Shot 2021-04-07 at 12 55 25 PM
- Table head's background color goes on top of the container div's borderline.
Screen Shot 2021-04-07 at 12 59 00 PM
-  the very end of the bottom border from `.MuiTableCell-root` interferes with the container div's borderline.
Screen Shot 2021-04-07 at 12 57 23 PM

### PR DESCRIPTION
**Pull request by kc-leung**
fix #16 

- Added Dynamic border radius styling for thead tr first and last child
- Added border bottom styling for tfoot tr fist child when round border is required
- Added Dynamic styling border styling for table container
- Moved useStyles function from table main file index.js into a separate file named useStyles.js under the same folder

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -53,6 +53,20 @@ const useStyles = makeStyles((theme) => ({
...
+    },
+
+    '& thead tr:last-child th:last-child': {
+      backgroundColor: '#FF0000',
+      'border-top-right-radius': 10,
+    },
+
+    '& tfoot tr:last-child td:first-child': {
+      'border-bottom': 0,
+    },
```
Comment (DoParkEQ) [inline src/index.js:69]: Not a bad idea, but I am worried that it could lead to another styling issue when the container's border radius is different than the hard-coded value. What do you think about dynamically adjust border radius by passing variables? Perhaps we can make its value to be inherited from its parent container

```jsx
  '& thead tr:last-child th:first-child': {
      backgroundColor: '#FF0000',
      'border-top-left-radius':({radius}) => radius,
    },
(...)
const useStyles = styles({radius});
```

Comment (DoParkEQ) [reply src/index.js:69]: Also I'd like to mention that the styling issue is only persistent with the table without the top toolbar. For default table form, border should be always square. 
Screen Shot 2021-04-08 at 12 26 50 PM

Comment (kc-leung) [reply src/index.js:69]: yea, it should be dynamically assigned the radius. If there is not prop for round table then it stays square. I will test it how it works

File: src/index.js [hunk 2]
```diff
@@ -193,9 +169,9 @@ export const Table = ({
       toggleSortBy(sortBy[0].id, sortBy[0].desc, false)
     }
   }, [sortBy])
-  
+
   return (
-    <>
+    <div className={'tableMainContainer ' + `${classes.tableMainContainer}`}>
```
Comment (DoParkEQ) [inline src/index.js:174]: Could you tell me why the `className` is combined with `tableMainContainer`?

File: src/useStyles.js [hunk 3]
```diff
@@ -0,0 +1,54 @@
+import { makeStyles } from '@material-ui/core/styles'
+
+const useStyles = (borderStyle) => makeStyles((theme) => {
+  const containerBorderStyle = (borderStyle.size && borderStyle.type) && {
```
Comment (DoParkEQ) [inline src/useStyles.js:4]: we can probably cut out the conditional statement as both `size` and `type` will contain values because of `propType`

File: src/index.js [hunk 4]
```diff
@@ -330,6 +312,11 @@ Table.defaultProps = {
   remember: {},
   extendColumns: false,
   downloadFn: saveData,
+  borderStyle: {
```
Comment (DoParkEQ) [inline src/index.js:315]: Instead of another abstraction, how about we take the actual CSS border attributes? For example: 
```jsx
borderStyle: {
   borderStyle: 'solid',
   borderRadius: 10,
   borderWidth: 2, 
} 
```
This way we can ensure that the component stays compatible with CSS syntax while users don't need to memorize keys for this particular prop.

Comment (DoParkEQ) [reply src/index.js:315]: Also, few more suggestions — 1) this will need a mechanism to handle shorthanded border attribute. 2) let's keep border style deactivated by default

File: src/useStyles.js [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+    border: `${borderStyle.size}px ${borderStyle.type} ${borderStyle.color ? borderStyle.color : 'black'}`,
+    'border-radius': `${borderStyle.radius > 0 ? borderStyle.radius : 0}px`,
+  }
+
+  const tableBorderRadius = borderStyle.radius > 0 && {
```
Comment (DoParkEQ) [inline src/useStyles.js:9]: border-radius is still in effect when there is a toolbar on top of the column heads:

Screen Shot 2021-04-12 at 10 26 31 AM

Comment (kc-leung) [reply src/useStyles.js]: just fixed the problem and added isBorder prop for the default values. Let me know what you think.

File: src/useStyles.js [hunk 6]
```diff
@@ -2,20 +2,22 @@ import { makeStyles } from '@material-ui/core/styles'
 
 const useStyles = (borderOptions) => makeStyles((theme) => {
   const containerBorderStyle = borderOptions.isBorder === true && {
-    border: `${borderOptions.borderStyle.size}px ${borderOptions.borderStyle.type} ${borderOptions.borderStyle.color ? borderOptions.borderStyle.color : 'black'}`,
-    'border-radius': `${borderOptions.borderStyle.radius > 0 ? borderOptions.borderStyle.radius : 0}px`,
+    borderWidth: `${borderOptions.borderStyles.borderWidth ? borderOptions.borderStyles.borderWidth : 2}px`,
+    borderStyle: `${borderOptions.borderStyles.borderStyle ? borderOptions.borderStyles.borderStyle : 'solid'}`,
+    borderColor: `${borderOptions.borderStyles.borderColor ? borderOptions.borderStyles.borderColor : 'black'}`,
+    borderRadius: `${borderOptions.borderStyles.borderRadius > 0 ? borderOptions.borderStyles.borderRadius : 0}px`,
```
Comment (DoParkEQ) [inline src/useStyles.js:8]: Do we need conditional statements here when `borderStyles`'s default values are set by PropTypes?

Comment (DoParkEQ) [reply src/useStyles.js:8]: also let's set default border style to :
```css
border: 1px solid #e0e0e0
border-radius: 4px

**Review by DoParkEQ — APPROVED** [review]

File: src/useStyles.js (hunk 6 above)
Comment (kc-leung) [reply src/useStyles.js:8]: problem is when the user pass a value lets say only border-radius the default values won't take effect only the passed border-radius

File: src/useStyles.js [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+const useStyles = (borderOptions) => makeStyles((theme) => {
+  const containerBorderStyle = borderOptions.isBorder === true && {
+    borderWidth: `${borderOptions.borderStyles.borderWidth ? borderOptions.borderStyles.borderWidth : 1}px`,
+    borderStyle: `${borderOptions.borderStyles.borderStyle ? borderOptions.borderStyles.borderStyle : 'solid'}`,
+    borderColor: `${borderOptions.borderStyles.borderColor ? borderOptions.borderStyles.borderColor : '#e0e0e0'}`,
+    borderRadius: `${borderOptions.borderStyles.borderRadius ? borderOptions.borderStyles.borderRadius : 4}px`,
+    '& tfoot tr:last-child td:first-child': {
+      'border-bottom': 0,
+    },
+  }
```
Comment (DoParkEQ) [inline src/useStyles.js:12]: I feel like this part could be shortened with object restructuring. How about this?
```jsx
const defaultBorderStyle = {
  border: '1px solid #e0e0e0',
  borderRadius: 4,
}

const useStyles = ({ isBorder, 
borderStyles: {
    borderRadius, 
    borderWidth, 
    borderStyle, 
    borderColor
}, toolbar }) => makeStyles((theme) => {

  const containerBorderStyle = isBorder && {
    ...defaultBorderStyle,
    borderWidth,
    borderStyle,
    borderColor,
    borderRadius,
    '& tfoot tr:last-child td:first-child': {
      'border-bottom': 0,
    },
  }

File: src/index.js [hunk 8]
```diff
@@ -118,8 +93,16 @@ export const Table = ({
   remember,
   extendColumns,
   downloadFn,
+  borderStyles,
+  isBorder,
 }) => {
-  const classes = useStyles()
+  const borderOptions = {
+    borderStyles,
```
Comment (DoParkEQ) [inline src/index.js:100]: I think shorthand borderstyling support is missing
e.g. `1px solid black`

**Review by woozyking — APPROVED** [review]
looks good. as a general suggestion, you can add screenshots (sometimes video recordings) for before/after the change to help reviewers with visual context if they don't have local setup readily available
